#!/usr/bin/env python
from distutils.sysconfig import get_config_var
import os
import sys
libdir=get_config_var("LIBPL")
libfile='python'+get_config_var("VERSION")
inc=get_config_var("INCLUDEPY")
out=""
args = ("".join(sys.argv[1:])).lower()
if "include" in args:
	out += " -I%s " % inc
if "link" in args:
	out +=  "-L%s -l%s" % (libdir,libfile)
if out=="":
	sys.stderr.write("Syntax for python_compilation_flags utility:\npython_compilation_flags include #for include flags\npython_compilation_flags link #for link flags.  Can also put both.\n")
else:
	print  out
