ifneq (clean,$(MAKECMDGOALS))
include ${COSMOSIS_SRC_DIR}/config/compilers.mk
endif

$(info ${COSMOSIS_SRC_DIR})

include ${COSMOSIS_SRC_DIR}/config/subdirs.mk

# SUBDIRS=datablock
SUBDIRS=datablock samplers
