#!/usr/bin/env bash

if [ $# -ne 1 ]; then
  echo "Usage: $0 <db-file>"
  exit 1
fi

fname="$1"

if [ ! -r $fname ]; then
  echo "File $fname does not exist or is not readable"
  exit 1
fi

sqlite3 -header -column $fname "select * from Samples ORDER BY sample"
