
/* These code/friendly names are generated
   automatically by the script 
   des-pipe/glue/bin/generate_friendly_names.py
   from the file des-pipe/glue/section_names.txt

   If you want to add friendly section names please
   modify that latter file. 
 */

#ifdef _H_DES_SECTION_NAME
#else
#define _H_DES_SECTION_NAME

#define COSMOLOGICAL_PARAMETERS_SECTION "COSMOPAR"
#define HALO_MODEL_PARAMETERS_SECTION "HALOPAR"
#define INTRINSIC_ALIGNMENT_PARAMETERS_SECTION "IA_PARAMS"
#define BARYON_PARAMETERS_SECTION "BARYON_PAR"
#define SHEAR_CALIBRATION_PARAMETERS_SECTION "SHEAR_CAL_PAR"
#define NUMBER_DENSITY_PARAMS_SECTION "NZ_PARAMS"
#define LIKELIHOODS_SECTION "LIKELIHOODS"
#define WL_NUMBER_DENSITY_SECTION "NZ_WL"
#define MATTER_POWER_NL_SECTION "PK_NL"
#define MATTER_POWER_LIN_SECTION "PK_LIN"
#define SHEAR_XI_SECTION "SHEAR_XI"
#define SHEAR_CL_SECTION "SHEAR_CL"
#define GALAXY_CL_SECTION "GAL_CL"
#define CMB_CL_SECTION "CMB_CL"
#define LSS_AUTOCORRELATION_SECTION "LSS_ACF"
#define GAL_MATTER_POWER_LIN_SECTION "GAL_PK_LIN"
#define LINEAR_CDM_TRANSFER_SECTION "LIN_TRANSFER"
#define SIGMA_R_LIN_SECTION "SIGMAR_LIN"
#define SIGMA_R_NL_SECTION "SIGMAR_NL"
#define PLANCK_SECTION "PLANCK"
#define INTRINSIC_ALIGNMENT_FIELD_SECTION "IA_FIELD"
#define SHEAR_CALIBRATION_SECTION "SHEAR_CAL"
#define BIAS_FIELD_SECTION "BIAS_FIELD"
#define DISTANCES_SECTION "DISTANCES"
#define DE_EQUATION_OF_STATE_SECTION "W_OF_A"

#endif

